# Generated by Django 3.1.4 on 2021-05-07 14:34

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30, verbose_name='Название')),
                ('describe', ckeditor.fields.RichTextField(default='', verbose_name='Описание')),
                ('date', models.DateTimeField(auto_now=True, null=True, verbose_name='Время')),
            ],
            options={
                'verbose_name': 'Информация',
                'verbose_name_plural': 'Информация',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30, verbose_name='Название')),
                ('describe', models.TextField(default='', verbose_name='Описание')),
                ('date', models.DateTimeField(auto_now=True, null=True, verbose_name='Время')),
            ],
            options={
                'verbose_name': 'Вопросы для часто задаваемых вопросов',
                'verbose_name_plural': 'Вопросы для часто задаваемых вопросов',
            },
        ),
    ]
