# Generated by Django 3.1.4 on 2021-05-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonus', '0003_auto_20210510_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invation',
            name='count',
            field=models.IntegerField(default=0, verbose_name='Количество приглашшенных пользователей'),
        ),
        migrations.AlterField(
            model_name='invation',
            name='hashurl',
            field=models.CharField(default='AXKXI', max_length=30, verbose_name='Хэш для url'),
        ),
    ]
