# Generated by Django 3.1.4 on 2021-05-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonus', '0004_auto_20210510_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invation',
            name='hashurl',
            field=models.CharField(default='', max_length=30, verbose_name='Хэш для url'),
        ),
    ]
