# Generated by Django 3.1.4 on 2021-05-16 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0019_auto_20210516_1021'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bonus', '0006_auto_20210510_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=30, verbose_name='Оглавление бонуса')),
                ('describe', models.TextField(default='', verbose_name='Описание бонусна')),
                ('points', models.CharField(default='', max_length=30, verbose_name='Вознограждение')),
            ],
            options={
                'verbose_name': 'Бонус',
                'verbose_name_plural': 'Бонусы',
            },
        ),
        migrations.CreateModel(
            name='BonusGeneral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0, verbose_name='Уровень')),
                ('title', models.CharField(default='', max_length=30, verbose_name='Оглавление бонусного уровня')),
                ('describe', models.TextField(default='', verbose_name='Описание бонусного уровня')),
                ('points', models.TextField(default='', verbose_name='Сколько очков')),
            ],
            options={
                'verbose_name': 'Уровень бонуса',
                'verbose_name_plural': 'Уровни бонусов',
            },
        ),
        migrations.CreateModel(
            name='RelationBonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus', models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, related_name='bonus', to='bonus.bonus', verbose_name='Бонус')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, related_name='location', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Связь пользователя с бонусами',
                'verbose_name_plural': 'Связь пользователей с бонусами',
            },
        ),
        migrations.AddField(
            model_name='bonus',
            name='level',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, related_name='bonusgeneral', to='bonus.bonusgeneral', verbose_name='выбор уровня бонуса'),
        ),
        migrations.AddField(
            model_name='bonus',
            name='location',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, related_name='location', to='conversation.location', verbose_name='Место бонуса'),
        ),
    ]
