# Generated by Django 3.1.4 on 2021-05-21 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonus', '0007_auto_20210516_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonus',
            name='forUser',
            field=models.BooleanField(default=False, verbose_name='Для пользователя'),
        ),
        migrations.AddField(
            model_name='bonusgeneral',
            name='forUser',
            field=models.BooleanField(default=False, verbose_name='Для пользователя'),
        ),
    ]
