# Generated by Django 3.1.4 on 2021-06-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonus', '0008_auto_20210521_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='points',
            field=models.CharField(default='', max_length=100, verbose_name='Вознограждение'),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='Оглавление бонуса'),
        ),
        migrations.AlterField(
            model_name='bonusgeneral',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='Оглавление бонусного уровня'),
        ),
        migrations.AlterField(
            model_name='info',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='invation',
            name='hashurl',
            field=models.CharField(default='', max_length=100, verbose_name='Хэш для url'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Вопрос'),
        ),
    ]
