# Generated by Django 3.1.4 on 2021-04-16 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('index', '0005_auto_20210414_1532'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdata',
            options={'verbose_name': 'Дополнительные поля для пользователя'},
        ),
        migrations.AddField(
            model_name='userdata',
            name='avavtar',
            field=models.CharField(blank=True, max_length=30, verbose_name='фото'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='appleId',
            field=models.CharField(blank=True, max_length=30, verbose_name='токен авторизации appleId'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='facebook',
            field=models.CharField(blank=True, max_length=30, verbose_name='токен авторизации facebook'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='google',
            field=models.CharField(blank=True, max_length=30, verbose_name='токен авторизации google'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='location',
            field=models.CharField(blank=True, max_length=30, verbose_name='локация'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='number',
            field=models.CharField(max_length=30, verbose_name='номр телефона'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='moreData', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='vk',
            field=models.CharField(blank=True, max_length=30, verbose_name='токен авторизации vk'),
        ),
    ]
