# Generated by Django 3.1.4 on 2021-05-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_auto_20210425_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='allowPush',
            field=models.BooleanField(default=True, verbose_name='разрешить уыедомления'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='blocked',
            field=models.BooleanField(default=False, verbose_name='заблокированный'),
        ),
    ]
