# Generated by Django 3.1.4 on 2021-05-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_auto_20210501_1425'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdata',
            options={'verbose_name': 'Дополнительное поле для пользователя', 'verbose_name_plural': 'Дополнительные поля для пользователя'},
        ),
        migrations.AlterField(
            model_name='userdata',
            name='blocked',
            field=models.BooleanField(default=False, verbose_name='заблокирован'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='number',
            field=models.CharField(max_length=30, verbose_name='номер телефона'),
        ),
    ]
