# Generated by Django 3.1.4 on 2021-05-07 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('index', '0010_auto_20210503_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Push',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30, verbose_name='Оглавление уведомления')),
                ('describe', models.TextField(default='', verbose_name='Описание')),
                ('photo', models.ImageField(default='', upload_to='static', verbose_name='Фото')),
                ('slug', models.CharField(blank=True, max_length=30, verbose_name='Для чего это уведомление')),
            ],
            options={
                'verbose_name': 'Пуш уведомление',
                'verbose_name_plural': 'Пуш уведомления',
            },
        ),
        migrations.AlterField(
            model_name='userdata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moreData', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
