# Generated by Django 3.1.4 on 2021-05-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_auto_20210507_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='push',
            name='slug',
            field=models.CharField(max_length=30, verbose_name='Для чего это уведомление'),
        ),
        migrations.AlterField(
            model_name='push',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Оглавление уведомления'),
        ),
    ]
