# Generated by Django 3.1.4 on 2021-05-07 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('index', '0013_support'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='support',
            options={'verbose_name': 'Вопрос обратной связи', 'verbose_name_plural': 'Вопросы обратной информации'},
        ),
        migrations.RemoveField(
            model_name='support',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='support',
            name='slug',
        ),
        migrations.AddField(
            model_name='support',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Просмотрено'),
        ),
        migrations.AddField(
            model_name='support',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='supportUser', to=settings.AUTH_USER_MODEL, verbose_name='Сообщение от'),
        ),
        migrations.AlterField(
            model_name='support',
            name='describe',
            field=models.TextField(default='', verbose_name='Описание проблемы'),
        ),
        migrations.AlterField(
            model_name='support',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Оглавление запроса'),
        ),
    ]
