# Generated by Django 3.1.4 on 2021-05-07 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0014_auto_20210507_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Главная')),
                ('email', models.CharField(max_length=30, verbose_name='Почта')),
                ('describe', models.TextField(default='', verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Конфигурация приложение',
                'verbose_name_plural': 'Конфигурация приложения',
            },
        ),
    ]
