# Generated by Django 3.1.4 on 2021-05-07 16:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0015_general'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general',
            name='describe',
            field=ckeditor.fields.RichTextField(default='', verbose_name='Описание'),
        ),
    ]
