# Generated by Django 3.1.4 on 2021-05-10 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0017_auto_20210510_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='general',
            name='appUrl',
            field=models.TextField(default='', verbose_name='Ссылка на приложение'),
        ),
    ]
