# Generated by Django 3.1.4 on 2021-05-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0018_general_appurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='avatar',
            field=models.ImageField(blank=True, default='', upload_to='static', verbose_name='фото'),
        ),
    ]
