# Generated by Django 3.1.4 on 2021-05-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0019_auto_20210515_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='isCompany',
            field=models.BooleanField(default=False, verbose_name='Является ли профиль компанией'),
        ),
    ]
