# Generated by Django 3.1.4 on 2021-05-16 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0020_userdata_iscompany'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='isCompany',
        ),
    ]
