# Generated by Django 3.1.4 on 2021-05-16 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0019_auto_20210516_1021'),
        ('index', '0021_remove_userdata_iscompany'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='location',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, related_name='user_location', to='conversation.location', verbose_name='Адрес'),
        ),
    ]
