# Generated by Django 3.1.4 on 2021-05-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0022_auto_20210516_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='push',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Оглавление уведомления'),
        ),
    ]
