# Generated by Django 3.1.4 on 2021-05-19 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0023_auto_20210519_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='push',
            name='slug',
            field=models.CharField(max_length=50, verbose_name='Для чего это уведомление'),
        ),
    ]
