# Generated by Django 3.1.4 on 2021-05-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0024_auto_20210519_1314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='support',
            options={'verbose_name': 'Вопрос обратной связи', 'verbose_name_plural': 'Вопрос обратной связи'},
        ),
        migrations.AddField(
            model_name='support',
            name='isAdmin',
            field=models.BooleanField(default=False, verbose_name='Выберите если это вы пишите пользователю'),
        ),
    ]
