# Generated by Django 3.1.4 on 2021-05-21 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0026_auto_20210521_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='general',
            name='appUrl',
        ),
        migrations.AddField(
            model_name='general',
            name='AppStore',
            field=models.TextField(default='', verbose_name='Ссылка на приложение в апп сторе'),
        ),
        migrations.AddField(
            model_name='general',
            name='PlayMarket',
            field=models.TextField(default='', verbose_name='Ссылка на приложение в плей маркете'),
        ),
        migrations.AlterField(
            model_name='support',
            name='email',
            field=models.CharField(default='', max_length=30, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='support',
            name='title',
            field=models.CharField(default='', max_length=30, verbose_name='Оглавление запроса'),
        ),
    ]
