# Generated by Django 3.1.4 on 2021-06-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0030_auto_20210606_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='avatar',
            field=models.ImageField(blank=True, default='', upload_to='', verbose_name='фото'),
        ),
    ]
