# Generated by Django 3.1.4 on 2021-06-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0031_auto_20210607_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='avatar',
            field=models.ImageField(blank=True, default='', upload_to='static', verbose_name='фото'),
        ),
    ]
