# Generated by Django 3.1.4 on 2021-06-08 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0032_auto_20210607_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='passportId',
            field=models.CharField(blank=True, max_length=100, verbose_name='Номер пасспорта'),
        ),
    ]
