# Generated by Django 3.1.4 on 2021-06-19 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0033_userdata_passportid'),
    ]

    operations = [
        migrations.AddField(
            model_name='push',
            name='time',
            field=models.CharField(default='* * * * *', max_length=50, verbose_name='Время отправки пуша ()'),
        ),
    ]
