# Generated by Django 3.1.4 on 2021-04-14 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raiting', models.IntegerField()),
                ('describe', models.TextField()),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('userFrom', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='from_reviews', to=settings.AUTH_USER_MODEL)),
                ('userTo', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='to_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('userFrom', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='from_messages', to=settings.AUTH_USER_MODEL)),
                ('userTo', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='to_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(default='', max_length=30)),
                ('active', models.BooleanField(default=True)),
                ('status', models.IntegerField(default=1)),
                ('title', models.CharField(default='', max_length=30)),
                ('describe', models.TextField(default='')),
                ('photo', models.ImageField(default='', upload_to='static')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('company', models.OneToOneField(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='company_aplications', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.RESTRICT, related_name='user_aplications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
