# Generated by Django 3.1.4 on 2021-04-15 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0002_auto_20210415_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applications',
            name='weight',
        ),
    ]
