# Generated by Django 3.1.4 on 2021-04-15 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0003_remove_applications_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applications',
            name='typeof',
        ),
    ]
