# Generated by Django 3.1.4 on 2021-04-15 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0004_remove_applications_typeof'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='weight',
            field=models.IntegerField(default=1),
        ),
    ]
