# Generated by Django 3.1.4 on 2021-04-15 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0005_applications_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='typeOf',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.RESTRICT, related_name='user_aplications', to='conversation.typeof'),
        ),
    ]
