# Generated by Django 3.1.4 on 2021-04-16 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conversation', '0006_applications_typeof'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applications',
            options={'verbose_name': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='messages',
            options={'verbose_name': 'Сообщения'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Отзывы'},
        ),
        migrations.AlterField(
            model_name='applications',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активный'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='company',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='company_aplications', to=settings.AUTH_USER_MODEL, verbose_name='выбор компании'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='date',
            field=models.DateTimeField(null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='describe',
            field=models.TextField(default='', verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='location',
            field=models.CharField(default='', max_length=30, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='photo',
            field=models.ImageField(default='', upload_to='static', verbose_name='фото'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='status',
            field=models.IntegerField(choices=[(0, 'ожидается'), (1, 'в пути'), (2, 'выполнено'), (3, 'отклонено')], default=1, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='title',
            field=models.CharField(default='', max_length=30, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='typeOf',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.RESTRICT, related_name='user_aplications', to='conversation.typeof', verbose_name='К какому типу принадлежит'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.RESTRICT, related_name='user_aplications', to=settings.AUTH_USER_MODEL, verbose_name='выбор пользователя'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='weight',
            field=models.IntegerField(default=1, verbose_name='Вес'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='date',
            field=models.DateTimeField(null=True, verbose_name='время'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='message',
            field=models.TextField(verbose_name='тело письма'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='userFrom',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='from_messages', to=settings.AUTH_USER_MODEL, verbose_name='Сообщение от'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='userTo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='to_messages', to=settings.AUTH_USER_MODEL, verbose_name='Сообщение для'),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(null=True, verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='review',
            name='describe',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='review',
            name='raiting',
            field=models.IntegerField(verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='review',
            name='userFrom',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='from_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Отзыв от'),
        ),
        migrations.AlterField(
            model_name='review',
            name='userTo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='to_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Отзыв для'),
        ),
    ]
