# Generated by Django 3.1.4 on 2021-04-16 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0007_auto_20210416_0758'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=30, verbose_name='Адрес')),
                ('describe', models.TextField(default='', verbose_name='Данные')),
            ],
            options={
                'verbose_name': 'Адреса',
            },
        ),
        migrations.AlterModelOptions(
            name='typeof',
            options={'verbose_name': 'Типы грузов'},
        ),
        migrations.AlterField(
            model_name='typeof',
            name='describe',
            field=models.TextField(default='', verbose_name='Данные'),
        ),
        migrations.AlterField(
            model_name='typeof',
            name='title',
            field=models.CharField(default='', max_length=30, verbose_name='Название типа'),
        ),
    ]
