# Generated by Django 3.1.4 on 2021-04-16 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conversation', '0008_auto_20210416_0808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='userFrom',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='userTo',
        ),
        migrations.CreateModel(
            name='Commucate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userFrom', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='from_messages', to=settings.AUTH_USER_MODEL, verbose_name='Сообщение от')),
                ('userTo', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='to_messages', to=settings.AUTH_USER_MODEL, verbose_name='Сообщение для')),
            ],
            options={
                'verbose_name': 'Комнаты',
            },
        ),
    ]
