# Generated by Django 3.1.4 on 2021-04-16 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conversation', '0010_auto_20210416_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='company_aplications', to=settings.AUTH_USER_MODEL, verbose_name='выбор компании'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, related_name='user_aplications', to=settings.AUTH_USER_MODEL, verbose_name='выбор пользователя'),
        ),
    ]
