# Generated by Django 3.1.4 on 2021-04-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0011_auto_20210416_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='время'),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Время'),
        ),
    ]
