# Generated by Django 3.1.4 on 2021-05-01 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conversation', '0013_messages_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='company',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='company_aplications', to=settings.AUTH_USER_MODEL, verbose_name='выбор компании'),
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('describe', models.TextField(default='', verbose_name='описание')),
                ('application', models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, related_name='user_proposal', to='conversation.applications', verbose_name='выбор заявки')),
                ('company', models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, related_name='user_proposal', to=settings.AUTH_USER_MODEL, verbose_name='выбор пользователя')),
            ],
            options={
                'verbose_name': 'Предложение',
            },
        ),
    ]
