# Generated by Django 3.1.4 on 2021-05-01 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conversation', '0014_auto_20210501_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='company_aplications', to=settings.AUTH_USER_MODEL, verbose_name='выбор компании'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='typeOf',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.RESTRICT, related_name='user_aplications', to='conversation.typeof', verbose_name='К какому типу принадлежит'),
        ),
    ]
