# Generated by Django 3.1.4 on 2021-05-03 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0016_auto_20210503_1149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proposal',
            options={'verbose_name': 'Предложение от компании для заявок', 'verbose_name_plural': 'Предложениятот компаний для заявок'},
        ),
        migrations.AlterField(
            model_name='applications',
            name='weight',
            field=models.IntegerField(default=1, verbose_name='Вес (кг)'),
        ),
    ]
