# Generated by Django 3.1.4 on 2021-05-16 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0017_auto_20210503_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='location',
            field=models.CharField(default='', max_length=30, verbose_name='Адреса'),
        ),
    ]
