# Generated by Django 3.1.4 on 2021-05-18 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conversation', '0020_auto_20210518_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='company',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, related_name='user_proposal', to=settings.AUTH_USER_MODEL, verbose_name='выбор пользователя'),
        ),
    ]
