# Generated by Django 3.1.4 on 2021-05-19 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0022_auto_20210518_1909'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proposal',
            options={'verbose_name': 'Предложение от компании для заявок', 'verbose_name_plural': 'Предложения от компаний для заявок'},
        ),
        migrations.AlterField(
            model_name='location',
            name='title',
            field=models.CharField(default='', max_length=50, verbose_name='Адрес'),
        ),
    ]
