# Generated by Django 3.1.4 on 2021-05-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0023_auto_20210519_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applications',
            name='typeOf',
        ),
        migrations.AddField(
            model_name='applications',
            name='typeOf',
            field=models.ManyToManyField(to='conversation.Typeof'),
        ),
    ]
