# Generated by Django 3.1.4 on 2021-05-21 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0024_auto_20210521_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='weight',
            field=models.CharField(max_length=50, verbose_name='Вес (кг)'),
        ),
    ]
