# Generated by Django 3.1.4 on 2021-05-21 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0025_auto_20210521_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='typeOf',
            field=models.ManyToManyField(to='conversation.Typeof', verbose_name='Типы груов'),
        ),
    ]
