# Generated by Django 3.1.4 on 2021-06-07 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0027_auto_20210606_1612'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proposal',
            options={'verbose_name': 'Предложение для компании', 'verbose_name_plural': 'Предложения для компаний'},
        ),
    ]
