# Generated by Django 3.1.4 on 2021-06-07 17:12

import conversation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0029_auto_20210607_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='photo',
            field=models.ImageField(blank=True, default='', null=True, upload_to=conversation.models.nameFile, verbose_name='фото'),
        ),
    ]
