# Generated by Django 3.1.4 on 2021-06-07 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0033_auto_20210607_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='typeOf',
            field=models.ManyToManyField(blank=True, to='conversation.Typeof', verbose_name='Типы груов'),
        ),
    ]
