# Generated by Django 3.1.4 on 2021-06-07 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0034_auto_20210607_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='active',
            field=models.BooleanField(blank=True, default=True, verbose_name='Активный'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='describe',
            field=models.TextField(blank=True, default='', verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'ожидается'), (1, 'в пути'), (2, 'выполнено'), (3, 'отклонено')], default=1, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='weight',
            field=models.CharField(blank=True, max_length=50, verbose_name='Вес (кг)'),
        ),
    ]
