# Generated by Django 3.1.4 on 2021-06-07 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0035_auto_20210607_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='location',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.RESTRICT, related_name='us_loc', to='conversation.location', verbose_name='Адрес'),
        ),
    ]
